/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import domainModel.DichVu;
import domainModel.GioHang;
import domainModel.LichDatSanCT;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import service.ServiceDichVu;
import service.ServiceGioHang;
import service.ServiceLichDatSan;
import swing.model.StatusType;
import swing.swing.ScrollBar;

/**
 *
 * @author sethk
 */
public class FormService extends javax.swing.JPanel {

    DefaultTableModel model;
    DefaultTableModel model1;

    ServiceDichVu qldv = new ServiceDichVu();
    ServiceGioHang qlgh = new ServiceGioHang();
    ServiceLichDatSan qlds = new ServiceLichDatSan();

    List<GioHang> listOrder = new ArrayList<>();
    int index = -1;

    /**
     * Creates new form FormDS
     */
    public FormService() {
        initComponents();

        this.setBackground(new Color(0, 0, 0, 0));
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);

        JS2.setVerticalScrollBar(new ScrollBar());
        JS2.getVerticalScrollBar().setBackground(Color.WHITE);
        JS2.getViewport().setBackground(Color.WHITE);
        this.setBackground(new Color(0, 0, 0, 0));

        p.setBackground(Color.WHITE);
        JS2.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);

        panelBorder1.setBackground(new Color(0, 0, 0, 0));
        panelBorder2.setBackground(new Color(0, 0, 0, 0));
        panelBorder3.setBackground(new Color(0, 0, 0, 0));
        panelBorder4.setBackground(new Color(0, 0, 0, 0));
        panelBorder5.setBackground(new Color(0, 0, 0, 0));
        panelBorder6.setBackground(new Color(0, 0, 0, 0));
        panelBorder7.setBackground(new Color(0, 0, 0, 0));
        panelBorder8.setBackground(new Color(0, 0, 0, 0));
        loadGiaDichvu(qldv.getListGiaDv());

        fillToTable1(qlds.loadTableDV());
    }

    void loadGiaDichvu(List<Double> list) {
        jlWater.setText(list.get(0).toString());
        bimbim.setText(list.get(1).toString());
        quanAo.setText(list.get(2).toString());
        giay.setText(list.get(3).toString());
        bong.setText(list.get(4).toString());
        xucXich.setText(list.get(5).toString());
        coCa.setText(list.get(6).toString());
        revive.setText(list.get(7).toString());
    }

    void fillToTable1(List<LichDatSanCT> list) {
        model = (DefaultTableModel) tbDss.getModel();
        model.setRowCount(0);

        for (LichDatSanCT lds : list) {
            model.addRow(new Object[]{
                lds.getTenSan(),
                lds.getMaDS(),
                lds.getTenKh(),
                lds.getTrangThai() == 1 ? StatusType.RESERVED : StatusType.USING
            });
        }
    }

    ////Thinking
    void addRow(List<DichVu> list) {

    }

    void fillTableDv(List<GioHang> list) {
        model1 = (DefaultTableModel) tbListDv.getModel();
        model1.setRowCount(0);
        for (GioHang gioHang : list) {
            model1.addRow(new Object[]{
                gioHang.getTenDv(),
                gioHang.getSoLuong(),
                gioHang.getSoLuong() * gioHang.getGiaTien()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JS2 = new javax.swing.JScrollPane();
        panelSeth13 = new swing.component.PanelSeth1();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        panelBorder1 = new swing.swing.PanelBorder();
        jLabel2 = new javax.swing.JLabel();
        jlWater = new javax.swing.JLabel();
        jsNcLoc = new javax.swing.JSpinner();
        jlWater1 = new javax.swing.JLabel();
        buttonOutLine1 = new swing.controls.ButtonOutLine();
        buttonOutLine3 = new swing.controls.ButtonOutLine();
        panelBorder2 = new swing.swing.PanelBorder();
        jLabel3 = new javax.swing.JLabel();
        bimbim = new javax.swing.JLabel();
        jsSnack = new javax.swing.JSpinner();
        jlWater3 = new javax.swing.JLabel();
        buttonOutLine2 = new swing.controls.ButtonOutLine();
        buttonOutLine4 = new swing.controls.ButtonOutLine();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        panelBorder3 = new swing.swing.PanelBorder();
        jLabel4 = new javax.swing.JLabel();
        bong = new javax.swing.JLabel();
        jsBong = new javax.swing.JSpinner();
        jlWater5 = new javax.swing.JLabel();
        buttonOutLine5 = new swing.controls.ButtonOutLine();
        buttonOutLine6 = new swing.controls.ButtonOutLine();
        panelBorder4 = new swing.swing.PanelBorder();
        jLabel5 = new javax.swing.JLabel();
        coCa = new javax.swing.JLabel();
        jsCoca = new javax.swing.JSpinner();
        jlWater7 = new javax.swing.JLabel();
        buttonOutLine7 = new swing.controls.ButtonOutLine();
        buttonOutLine8 = new swing.controls.ButtonOutLine();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        panelBorder5 = new swing.swing.PanelBorder();
        jLabel6 = new javax.swing.JLabel();
        quanAo = new javax.swing.JLabel();
        jsQA = new javax.swing.JSpinner();
        jlWater9 = new javax.swing.JLabel();
        buttonOutLine9 = new swing.controls.ButtonOutLine();
        buttonOutLine10 = new swing.controls.ButtonOutLine();
        panelBorder6 = new swing.swing.PanelBorder();
        jLabel7 = new javax.swing.JLabel();
        giay = new javax.swing.JLabel();
        jsShose = new javax.swing.JSpinner();
        aaaa = new javax.swing.JLabel();
        buttonOutLine11 = new swing.controls.ButtonOutLine();
        buttonOutLine12 = new swing.controls.ButtonOutLine();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        panelBorder7 = new swing.swing.PanelBorder();
        jLabel8 = new javax.swing.JLabel();
        xucXich = new javax.swing.JLabel();
        jsXx = new javax.swing.JSpinner();
        jlWater6 = new javax.swing.JLabel();
        buttonOutLine13 = new swing.controls.ButtonOutLine();
        buttonOutLine14 = new swing.controls.ButtonOutLine();
        panelBorder8 = new swing.swing.PanelBorder();
        jLabel9 = new javax.swing.JLabel();
        revive = new javax.swing.JLabel();
        jsRv = new javax.swing.JSpinner();
        jlWater8 = new javax.swing.JLabel();
        buttonOutLine15 = new swing.controls.ButtonOutLine();
        buttonOutLine16 = new swing.controls.ButtonOutLine();
        panelSeth3 = new swing.component.PanelSeth();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbListDv = new swing.swing.Table();
        jLabel13 = new javax.swing.JLabel();
        panelSeth1 = new swing.component.PanelSeth();
        btnThemDV = new swing.controls.ButtonGradient();
        btnHuyDV = new swing.controls.ButtonGradient();
        btnThemDV1 = new swing.controls.ButtonGradient();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDss = new swing.swing.Table();

        setBackground(new java.awt.Color(255, 255, 255));

        JS2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelSeth13.setColor1(new java.awt.Color(134, 194, 211));
        panelSeth13.setColor2(new java.awt.Color(255, 239, 186));

        jLayeredPane2.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/water.png"))); // NOI18N

        jlWater.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jsNcLoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsNcLocKeyPressed(evt);
            }
        });

        jlWater1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jlWater1.setText("Nước Lọc");

        buttonOutLine1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-plus-20.png"))); // NOI18N
        buttonOutLine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOutLine1ActionPerformed(evt);
            }
        });

        buttonOutLine3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-minus-20.png"))); // NOI18N

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jlWater1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jsNcLoc, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(jlWater, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBorder1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(buttonOutLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonOutLine3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlWater1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jlWater, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsNcLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonOutLine1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOutLine3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane2.add(panelBorder1);

        panelBorder2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/snackk.png"))); // NOI18N

        bimbim.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jsSnack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsSnackKeyPressed(evt);
            }
        });

        jlWater3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jlWater3.setText("Bim Bim");

        buttonOutLine2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-plus-20.png"))); // NOI18N
        buttonOutLine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOutLine2ActionPerformed(evt);
            }
        });

        buttonOutLine4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-minus-20.png"))); // NOI18N

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBorder2Layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addComponent(buttonOutLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(buttonOutLine4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder2Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bimbim, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                    .addComponent(jsSnack))
                                .addComponent(jlWater3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelBorder2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlWater3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bimbim, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsSnack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonOutLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOutLine4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane2.add(panelBorder2);

        jLayeredPane3.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        panelBorder3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bong.png"))); // NOI18N

        bong.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jsBong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsBongKeyPressed(evt);
            }
        });

        jlWater5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jlWater5.setText("Bóng");

        buttonOutLine5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-plus-20.png"))); // NOI18N
        buttonOutLine5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOutLine5ActionPerformed(evt);
            }
        });

        buttonOutLine6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-minus-20.png"))); // NOI18N

        javax.swing.GroupLayout panelBorder3Layout = new javax.swing.GroupLayout(panelBorder3);
        panelBorder3.setLayout(panelBorder3Layout);
        panelBorder3Layout.setHorizontalGroup(
            panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jsBong, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(bong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBorder3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(buttonOutLine5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonOutLine6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(panelBorder3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlWater5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBorder3Layout.setVerticalGroup(
            panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlWater5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(bong, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsBong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonOutLine5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOutLine6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane3.add(panelBorder3);

        panelBorder4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/coca.png"))); // NOI18N

        coCa.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jsCoca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jsCoca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsCocaKeyPressed(evt);
            }
        });

        jlWater7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jlWater7.setText("Coca");

        buttonOutLine7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-plus-20.png"))); // NOI18N
        buttonOutLine7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOutLine7ActionPerformed(evt);
            }
        });

        buttonOutLine8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-minus-20.png"))); // NOI18N

        javax.swing.GroupLayout panelBorder4Layout = new javax.swing.GroupLayout(panelBorder4);
        panelBorder4.setLayout(panelBorder4Layout);
        panelBorder4Layout.setHorizontalGroup(
            panelBorder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder4Layout.createSequentialGroup()
                .addGroup(panelBorder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panelBorder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jsCoca, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(coCa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBorder4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(buttonOutLine7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonOutLine8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelBorder4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jlWater7)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelBorder4Layout.setVerticalGroup(
            panelBorder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlWater7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coCa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsCoca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonOutLine7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOutLine8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane3.add(panelBorder4);

        jLayeredPane4.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        panelBorder5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/clothes.png"))); // NOI18N

        quanAo.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jsQA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsQAKeyPressed(evt);
            }
        });

        jlWater9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jlWater9.setText("Quần Áo");

        buttonOutLine9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-plus-20.png"))); // NOI18N
        buttonOutLine9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOutLine9ActionPerformed(evt);
            }
        });

        buttonOutLine10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-minus-20.png"))); // NOI18N

        javax.swing.GroupLayout panelBorder5Layout = new javax.swing.GroupLayout(panelBorder5);
        panelBorder5.setLayout(panelBorder5Layout);
        panelBorder5Layout.setHorizontalGroup(
            panelBorder5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder5Layout.createSequentialGroup()
                .addGroup(panelBorder5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBorder5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jlWater9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBorder5Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(panelBorder5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelBorder5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jsQA, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                .addComponent(quanAo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBorder5Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(buttonOutLine9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(buttonOutLine10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelBorder5Layout.setVerticalGroup(
            panelBorder5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlWater9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quanAo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsQA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonOutLine9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOutLine10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane4.add(panelBorder5);

        panelBorder6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shoes.png"))); // NOI18N

        giay.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jsShose.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsShoseKeyPressed(evt);
            }
        });

        aaaa.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        aaaa.setText("Giày");

        buttonOutLine11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-plus-20.png"))); // NOI18N
        buttonOutLine11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOutLine11ActionPerformed(evt);
            }
        });

        buttonOutLine12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-minus-20.png"))); // NOI18N

        javax.swing.GroupLayout panelBorder6Layout = new javax.swing.GroupLayout(panelBorder6);
        panelBorder6.setLayout(panelBorder6Layout);
        panelBorder6Layout.setHorizontalGroup(
            panelBorder6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelBorder6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBorder6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jsShose, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                        .addComponent(giay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBorder6Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(buttonOutLine11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(buttonOutLine12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBorder6Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(aaaa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        panelBorder6Layout.setVerticalGroup(
            panelBorder6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aaaa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(giay, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsShose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonOutLine11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOutLine12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane4.add(panelBorder6);

        jLayeredPane5.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        panelBorder7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-sausage-100.png"))); // NOI18N

        xucXich.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jsXx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsXxKeyPressed(evt);
            }
        });

        jlWater6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jlWater6.setText("Xúc Xích");

        buttonOutLine13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-plus-20.png"))); // NOI18N
        buttonOutLine13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOutLine13ActionPerformed(evt);
            }
        });

        buttonOutLine14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-minus-20.png"))); // NOI18N

        javax.swing.GroupLayout panelBorder7Layout = new javax.swing.GroupLayout(panelBorder7);
        panelBorder7.setLayout(panelBorder7Layout);
        panelBorder7Layout.setHorizontalGroup(
            panelBorder7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelBorder7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jsXx, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(xucXich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBorder7Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(buttonOutLine13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonOutLine14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(panelBorder7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelBorder7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlWater6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBorder7Layout.setVerticalGroup(
            panelBorder7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder7Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlWater6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(xucXich, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsXx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonOutLine13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOutLine14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane5.add(panelBorder7);

        panelBorder8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/revive.png"))); // NOI18N

        revive.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jsRv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jsRvKeyPressed(evt);
            }
        });

        jlWater8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jlWater8.setText("Revive");

        buttonOutLine15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-plus-20.png"))); // NOI18N
        buttonOutLine15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOutLine15ActionPerformed(evt);
            }
        });

        buttonOutLine16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-minus-20.png"))); // NOI18N

        javax.swing.GroupLayout panelBorder8Layout = new javax.swing.GroupLayout(panelBorder8);
        panelBorder8.setLayout(panelBorder8Layout);
        panelBorder8Layout.setHorizontalGroup(
            panelBorder8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder8Layout.createSequentialGroup()
                .addGroup(panelBorder8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder8Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panelBorder8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jsRv, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(revive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBorder8Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(buttonOutLine15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonOutLine16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelBorder8Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jlWater8))
                    .addGroup(panelBorder8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelBorder8Layout.setVerticalGroup(
            panelBorder8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder8Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlWater8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(revive, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsRv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBorder8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonOutLine15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonOutLine16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane5.add(panelBorder8);

        javax.swing.GroupLayout panelSeth13Layout = new javax.swing.GroupLayout(panelSeth13);
        panelSeth13.setLayout(panelSeth13Layout);
        panelSeth13Layout.setHorizontalGroup(
            panelSeth13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeth13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSeth13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        panelSeth13Layout.setVerticalGroup(
            panelSeth13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeth13Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JS2.setViewportView(panelSeth13);

        panelSeth3.setColor1(new java.awt.Color(153, 102, 0));
        panelSeth3.setColor2(new java.awt.Color(123, 123, 245));

        tbListDv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên Dịch Vụ", "Số Lượng", "Thành Tiền"
            }
        ));
        jScrollPane2.setViewportView(tbListDv);

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("List Dịch Vụ");

        javax.swing.GroupLayout panelSeth3Layout = new javax.swing.GroupLayout(panelSeth3);
        panelSeth3.setLayout(panelSeth3Layout);
        panelSeth3Layout.setHorizontalGroup(
            panelSeth3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeth3Layout.createSequentialGroup()
                .addGroup(panelSeth3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSeth3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSeth3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        panelSeth3Layout.setVerticalGroup(
            panelSeth3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSeth3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        panelSeth1.setColor1(new java.awt.Color(241, 208, 62));
        panelSeth1.setColor2(new java.awt.Color(211, 184, 61));

        btnThemDV.setText("Thêm ");
        btnThemDV.setColor1(new java.awt.Color(57, 106, 252));
        btnThemDV.setColor2(new java.awt.Color(36, 36, 62));
        btnThemDV.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnThemDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDVActionPerformed(evt);
            }
        });

        btnHuyDV.setText("Hủy");
        btnHuyDV.setColor1(new java.awt.Color(57, 106, 252));
        btnHuyDV.setColor2(new java.awt.Color(36, 36, 62));
        btnHuyDV.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnHuyDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyDVActionPerformed(evt);
            }
        });

        btnThemDV1.setText("Sửa");
        btnThemDV1.setColor1(new java.awt.Color(57, 106, 252));
        btnThemDV1.setColor2(new java.awt.Color(36, 36, 62));
        btnThemDV1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnThemDV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDV1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSeth1Layout = new javax.swing.GroupLayout(panelSeth1);
        panelSeth1.setLayout(panelSeth1Layout);
        panelSeth1Layout.setHorizontalGroup(
            panelSeth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeth1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelSeth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHuyDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemDV, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(btnThemDV1, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelSeth1Layout.setVerticalGroup(
            panelSeth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeth1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnThemDV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(btnThemDV1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnHuyDV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        tbDss.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên Sân", "Mã Đs", "Tên KH", "Trạng Thái"
            }
        ));
        tbDss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDssMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDss);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JS2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(panelSeth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelSeth3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelSeth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(panelSeth3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(JS2, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jsNcLocKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsNcLocKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jsNcLocKeyPressed

    private void btnThemDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDVActionPerformed
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Chọn sân cần sử dụng dịch vụ !!!");
        } else {
            qlgh.addGioHang(listOrder);
        }
    }//GEN-LAST:event_btnThemDVActionPerformed

    private void btnHuyDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyDVActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnHuyDVActionPerformed

    private void btnThemDV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemDV1ActionPerformed

    private void jsSnackKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsSnackKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsSnackKeyPressed

    private void jsBongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsBongKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsBongKeyPressed

    private void jsCocaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsCocaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsCocaKeyPressed

    private void jsQAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsQAKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsQAKeyPressed

    private void jsShoseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsShoseKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsShoseKeyPressed

    private void jsXxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsXxKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsXxKeyPressed

    private void jsRvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jsRvKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jsRvKeyPressed

    private void buttonOutLine15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOutLine15ActionPerformed
        // TODO add your handling code here:
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Chọn sân cần sử dụng dịch vụ !!!");
        } else {
            listOrder.add(new GioHang("MD6", tbDss.getValueAt(index, 1).toString(), Integer.parseInt(jsRv.getValue().toString())));
        }
    }//GEN-LAST:event_buttonOutLine15ActionPerformed

    private void buttonOutLine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOutLine1ActionPerformed
        // TODO add your handling code here:
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Chọn sân cần sử dụng dịch vụ !!!");
        } else {
            listOrder.add(new GioHang("MDV1", tbDss.getValueAt(index, 1).toString(), Integer.parseInt(jsNcLoc.getValue().toString())));

        }
    }//GEN-LAST:event_buttonOutLine1ActionPerformed

    private void buttonOutLine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOutLine2ActionPerformed
        // TODO add your handling code here:
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Chọn sân cần sử dụng dịch vụ !!!");
        } else {
            listOrder.add(new GioHang("MDV2", tbDss.getValueAt(index, 1).toString(), Integer.parseInt(jsSnack.getValue().toString())));

        }
    }//GEN-LAST:event_buttonOutLine2ActionPerformed

    private void buttonOutLine9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOutLine9ActionPerformed
        // TODO add your handling code here:
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Chọn sân cần sử dụng dịch vụ !!!");
        } else {
            listOrder.add(new GioHang("MDV3", tbDss.getValueAt(index, 1).toString(), Integer.parseInt(jsQA.getValue().toString())));

        }

    }//GEN-LAST:event_buttonOutLine9ActionPerformed

    private void buttonOutLine11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOutLine11ActionPerformed
        // TODO add your handling code here:
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Chọn sân cần sử dụng dịch vụ !!!");
        } else {
            listOrder.add(new GioHang("MDV4", tbDss.getValueAt(index, 1).toString(), Integer.parseInt(jsShose.getValue().toString())));

        }

    }//GEN-LAST:event_buttonOutLine11ActionPerformed

    private void buttonOutLine13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOutLine13ActionPerformed
        // TODO add your handling code here:
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Chọn sân cần sử dụng dịch vụ !!!");
        } else {
            listOrder.add(new GioHang("MD6", tbDss.getValueAt(index, 1).toString(), Integer.parseInt(jsRv.getValue().toString())));
        }
        listOrder.add(new GioHang("MD5", tbDss.getValueAt(index, 1).toString(), Integer.parseInt(jsXx.getValue().toString())));

    }//GEN-LAST:event_buttonOutLine13ActionPerformed

    private void buttonOutLine5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOutLine5ActionPerformed
        // TODO add your handling code here:
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Chọn sân cần sử dụng dịch vụ !!!");
        } else {
            listOrder.add(new GioHang("MDV8 ", tbDss.getValueAt(index, 1).toString(), Integer.parseInt(jsBong.getValue().toString())));

        }

    }//GEN-LAST:event_buttonOutLine5ActionPerformed

    private void buttonOutLine7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOutLine7ActionPerformed
        // TODO add your handling code here:
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Chọn sân cần sử dụng dịch vụ !!!");
        } else {
            listOrder.add(new GioHang("MDV7", tbDss.getValueAt(index, 1).toString(), Integer.parseInt(jsCoca.getValue().toString())));

        }

    }//GEN-LAST:event_buttonOutLine7ActionPerformed

    private void tbDssMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDssMouseClicked
        // TODO add your handling code here:

        index = tbDss.getSelectedRow();

        fillTableDv(qlgh.getListOrder(tbDss.getValueAt(index, 1).toString()));
    }//GEN-LAST:event_tbDssMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JS2;
    private javax.swing.JLabel aaaa;
    private javax.swing.JLabel bimbim;
    private javax.swing.JLabel bong;
    private swing.controls.ButtonGradient btnHuyDV;
    private swing.controls.ButtonGradient btnThemDV;
    private swing.controls.ButtonGradient btnThemDV1;
    private swing.controls.ButtonOutLine buttonOutLine1;
    private swing.controls.ButtonOutLine buttonOutLine10;
    private swing.controls.ButtonOutLine buttonOutLine11;
    private swing.controls.ButtonOutLine buttonOutLine12;
    private swing.controls.ButtonOutLine buttonOutLine13;
    private swing.controls.ButtonOutLine buttonOutLine14;
    private swing.controls.ButtonOutLine buttonOutLine15;
    private swing.controls.ButtonOutLine buttonOutLine16;
    private swing.controls.ButtonOutLine buttonOutLine2;
    private swing.controls.ButtonOutLine buttonOutLine3;
    private swing.controls.ButtonOutLine buttonOutLine4;
    private swing.controls.ButtonOutLine buttonOutLine5;
    private swing.controls.ButtonOutLine buttonOutLine6;
    private swing.controls.ButtonOutLine buttonOutLine7;
    private swing.controls.ButtonOutLine buttonOutLine8;
    private swing.controls.ButtonOutLine buttonOutLine9;
    private javax.swing.JLabel coCa;
    private javax.swing.JLabel giay;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlWater;
    private javax.swing.JLabel jlWater1;
    private javax.swing.JLabel jlWater3;
    private javax.swing.JLabel jlWater5;
    private javax.swing.JLabel jlWater6;
    private javax.swing.JLabel jlWater7;
    private javax.swing.JLabel jlWater8;
    private javax.swing.JLabel jlWater9;
    private javax.swing.JSpinner jsBong;
    private javax.swing.JSpinner jsCoca;
    private javax.swing.JSpinner jsNcLoc;
    private javax.swing.JSpinner jsQA;
    private javax.swing.JSpinner jsRv;
    private javax.swing.JSpinner jsShose;
    private javax.swing.JSpinner jsSnack;
    private javax.swing.JSpinner jsXx;
    private swing.swing.PanelBorder panelBorder1;
    private swing.swing.PanelBorder panelBorder2;
    private swing.swing.PanelBorder panelBorder3;
    private swing.swing.PanelBorder panelBorder4;
    private swing.swing.PanelBorder panelBorder5;
    private swing.swing.PanelBorder panelBorder6;
    private swing.swing.PanelBorder panelBorder7;
    private swing.swing.PanelBorder panelBorder8;
    private swing.component.PanelSeth panelSeth1;
    private swing.component.PanelSeth1 panelSeth13;
    private swing.component.PanelSeth panelSeth3;
    private javax.swing.JLabel quanAo;
    private javax.swing.JLabel revive;
    private swing.swing.Table tbDss;
    private swing.swing.Table tbListDv;
    private javax.swing.JLabel xucXich;
    // End of variables declaration//GEN-END:variables
}
