/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import domainModel.GioHang;
import domainModel.LichDatSanCT;
import global.Global;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import service.ServiceGioHang;
import service.ServiceLichDatSan;
import service.ServiceTaiKhoan;
import service.ServiceThanhToan;
import swing.model.StatusType;
import swing.swing.ScrollBar;

/**
 *
 * @author sethk
 */
public class FormThanhToan extends javax.swing.JPanel implements Runnable {

    DefaultTableModel model;
    DefaultTableModel model1;
    int index = -1;
    int index1 = -1;
    ServiceLichDatSan qlds = new ServiceLichDatSan();
    ServiceGioHang qlgh = new ServiceGioHang();
    service.ServiceTaiKhoan qltk = new ServiceTaiKhoan();
    ServiceThanhToan qltt = new ServiceThanhToan();

    /**
     * Creates new form FormThanhToan
     */
    public FormThanhToan() {
        initComponents();

        txtNguoiLap.setText(qltk.getNameStaff(Global.getUser()));
        txtNguoiLap.setEnabled(false);
        txtTT.setEnabled(false);
        txtTenKH.setEnabled(false);
        txtTienCoc.setEnabled(false);

        line.setSize(WIDTH, 1);
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);

        spTable1.setVerticalScrollBar(new ScrollBar());
        spTable1.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable1.getViewport().setBackground(Color.WHITE);

        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        spTable1.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);

        fillTable(qlds.loadTableDV());

        ////////////////////////////////////////////
        Thread t = new Thread(this);
        t.start();
    }

    public void fillTable(List<LichDatSanCT> list) {
        model = (DefaultTableModel) tbDss.getModel();
        model.setRowCount(0);
        for (LichDatSanCT lds : list) {
            model.addRow(new Object[]{
                lds.getMaDS(),
                lds.getTenSan(),
                lds.getLoai(),
                lds.getCa(),
                lds.getTenKh(),
                lds.getTrangThai() == 1 ? StatusType.RESERVED : StatusType.USING
            });
        }

    }

    void fillTableDv(List<GioHang> list) {
        model1 = (DefaultTableModel) tbListDv.getModel();
        model1.setRowCount(0);
        for (GioHang gioHang : list) {
            model1.addRow(new Object[]{
                gioHang.getTenDv(),
                gioHang.getSoLuong(),
                gioHang.getGiaTien(),
                gioHang.getSoLuong() * gioHang.getGiaTien()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSeth3 = new swing.component.PanelSeth();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        line = new javax.swing.JPanel();
        button4 = new swing.controls.Button();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtNguoiLap = new swing.controls.TextField();
        txtTongTien = new swing.controls.TextField();
        txtTienCoc = new swing.controls.TextField();
        txtTT = new swing.controls.TextField();
        jLabel11 = new javax.swing.JLabel();
        txtTenKH = new swing.controls.TextField();
        spTable = new javax.swing.JScrollPane();
        tbDss = new swing.swing.Table();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        spTable1 = new javax.swing.JScrollPane();
        tbListDv = new swing.swing.Table();
        panelSeth4 = new swing.component.PanelSeth();
        cb2 = new javax.swing.JCheckBox();
        cb5 = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));

        panelSeth3.setColor1(new java.awt.Color(153, 102, 0));
        panelSeth3.setColor2(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(220, 216, 216));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/mBill.png"))); // NOI18N
        jLabel4.setText("    Thanh Toán");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(220, 216, 216));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/profit.png"))); // NOI18N
        jLabel5.setText(" Tổng Tiền");

        line.setBackground(new java.awt.Color(255, 255, 255));
        line.setPreferredSize(new java.awt.Dimension(0, 1));

        javax.swing.GroupLayout lineLayout = new javax.swing.GroupLayout(line);
        line.setLayout(lineLayout);
        lineLayout.setHorizontalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        lineLayout.setVerticalGroup(
            lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        button4.setForeground(new java.awt.Color(204, 204, 204));
        button4.setText("Thanh Toán");
        button4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(220, 216, 216));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/stock.png"))); // NOI18N
        jLabel9.setText("Thành Tiền ");

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(220, 216, 216));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/client.png"))); // NOI18N
        jLabel10.setText(" Tiền  Cọc");

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(220, 216, 216));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/client.png"))); // NOI18N
        jLabel21.setText("  Người Lập");

        txtNguoiLap.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtNguoiLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNguoiLapActionPerformed(evt);
            }
        });

        txtTongTien.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienActionPerformed(evt);
            }
        });

        txtTienCoc.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtTienCoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienCocActionPerformed(evt);
            }
        });

        txtTT.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTTActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(220, 216, 216));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/client.png"))); // NOI18N
        jLabel11.setText("  Khách Hàng");

        txtTenKH.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSeth3Layout = new javax.swing.GroupLayout(panelSeth3);
        panelSeth3.setLayout(panelSeth3Layout);
        panelSeth3Layout.setHorizontalGroup(
            panelSeth3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeth3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSeth3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSeth3Layout.createSequentialGroup()
                        .addComponent(line, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSeth3Layout.createSequentialGroup()
                        .addGap(0, 98, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(panelSeth3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panelSeth3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSeth3Layout.createSequentialGroup()
                                .addGroup(panelSeth3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelSeth3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(panelSeth3Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addGroup(panelSeth3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTT, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTienCoc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNguoiLap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTenKH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSeth3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        panelSeth3Layout.setVerticalGroup(
            panelSeth3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeth3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelSeth3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSeth3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelSeth3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(panelSeth3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTienCoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(panelSeth3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelSeth3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNguoiLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelSeth3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );

        spTable.setBorder(null);

        tbDss.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Đs", "Tên Sân", "Loại", "Ca Đá", "Tên KH", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDssMouseClicked(evt);
            }
        });
        spTable.setViewportView(tbDss);

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Danh Sách Dịch Vụ");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Danh Sách Sân");

        tbListDv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên Dv", "Số Lượng", "Giá Tiền", "Thành Tiền"
            }
        ));
        spTable1.setViewportView(tbListDv);

        panelSeth4.setColor1(new java.awt.Color(153, 102, 0));
        panelSeth4.setColor2(new java.awt.Color(0, 0, 0));

        cb2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cb2.setForeground(new java.awt.Color(255, 255, 255));
        cb2.setText("Giảm 2% tổng bill");
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });

        cb5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cb5.setForeground(new java.awt.Color(255, 255, 255));
        cb5.setText("Giảm 5% tổng bill");
        cb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSeth4Layout = new javax.swing.GroupLayout(panelSeth4);
        panelSeth4.setLayout(panelSeth4Layout);
        panelSeth4Layout.setHorizontalGroup(
            panelSeth4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeth4Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(panelSeth4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb5)
                    .addComponent(cb2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSeth4Layout.setVerticalGroup(
            panelSeth4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeth4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(cb2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spTable, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                    .addComponent(spTable1))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelSeth3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSeth4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelSeth3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelSeth4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spTable, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        FormHD form = new FormHD();
        form.setVisible(true);
    }//GEN-LAST:event_button4ActionPerformed

    private void txtNguoiLapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNguoiLapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNguoiLapActionPerformed

    private void txtTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienActionPerformed

    private void txtTienCocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienCocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienCocActionPerformed

    private void txtTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTTActionPerformed

    private void tbDssMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDssMouseClicked
        // TODO add your handling code here:

        index = tbDss.getSelectedRow();

        fillTableDv(qlgh.getListOrder(tbDss.getValueAt(index, 0).toString()));

        int cada = (int) tbDss.getValueAt(index, 3);
        String mds = tbDss.getValueAt(index, 0).toString();
        Double tongTienDv = qltt.TongTien(tbDss.getValueAt(index, 0).toString());
        Double tongTien = tongTienDv + qltt.giaSan(mds, cada);
        Double tienCoc = qltt.tienDatCoc(mds);
        double ThanhTien = 0;

        if (cb2.isSelected()) {
            ThanhTien = tongTien - tienCoc - (tongTien * 0.02);
            txtTT.setText(String.valueOf(ThanhTien));
        } else if (cb5.isSelected()) {
            ThanhTien = tongTien - tienCoc - (tongTien * 0.05);
            txtTT.setText(String.valueOf(ThanhTien));
        } else {
            ThanhTien = tongTien - tienCoc;
            txtTT.setText(String.valueOf(ThanhTien));
        }

        txtTenKH.setText(tbDss.getValueAt(index, 4).toString());
        txtTienCoc.setText(tienCoc.toString());
        txtTongTien.setText(tongTien.toString());
        cb5.setSelected(false);
        cb2.setSelected(false);

    }//GEN-LAST:event_tbDssMouseClicked

    private void txtTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKHActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        // TODO add your handling code here:
        index = tbDss.getSelectedRow();

        fillTableDv(qlgh.getListOrder(tbDss.getValueAt(index, 0).toString()));

        int cada = (int) tbDss.getValueAt(index, 3);
        String mds = tbDss.getValueAt(index, 0).toString();
        Double tongTienDv = qltt.TongTien(tbDss.getValueAt(index, 0).toString());
        Double tongTien = tongTienDv + qltt.giaSan(mds, cada);
        Double tienCoc = qltt.tienDatCoc(mds);
        double ThanhTien = 0;
        if (cb5.isSelected() && cb2.isSelected()) {
            JOptionPane.showMessageDialog(null, "Không được áp dụng 2 mã giảm giá");
            cb5.setSelected(false);
        }
        if (cb2.isSelected()) {
            ThanhTien = tongTien - tienCoc - (tongTien * 0.02);
            txtTT.setText(String.valueOf(ThanhTien));
        } else {
            ThanhTien = tongTien - tienCoc;
            txtTT.setText(String.valueOf(ThanhTien));
        }


    }//GEN-LAST:event_cb2ActionPerformed

    private void cb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb5ActionPerformed
        // TODO add your handling code here:
        index = tbDss.getSelectedRow();
        index = tbDss.getSelectedRow();

        fillTableDv(qlgh.getListOrder(tbDss.getValueAt(index, 0).toString()));

        int cada = (int) tbDss.getValueAt(index, 3);
        String mds = tbDss.getValueAt(index, 0).toString();
        Double tongTienDv = qltt.TongTien(tbDss.getValueAt(index, 0).toString());
        Double tongTien = tongTienDv + qltt.giaSan(mds, cada);
        Double tienCoc = qltt.tienDatCoc(mds);
        double ThanhTien = 0;

        if (cb2.isSelected() && cb5.isSelected()) {
            JOptionPane.showMessageDialog(null, "Không được áp dụng 2 mã giảm giá");
            cb2.setSelected(false);
        }

        if (cb5.isSelected()) {
            ThanhTien = tongTien - tienCoc - (tongTien * 0.05);
            txtTT.setText(String.valueOf(ThanhTien));
        } else {
            ThanhTien = tongTien - tienCoc;
            txtTT.setText(String.valueOf(ThanhTien));
        }
    }//GEN-LAST:event_cb5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.controls.Button button4;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb5;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel line;
    private swing.component.PanelSeth panelSeth3;
    private swing.component.PanelSeth panelSeth4;
    private javax.swing.JScrollPane spTable;
    private javax.swing.JScrollPane spTable1;
    private swing.swing.Table tbDss;
    private swing.swing.Table tbListDv;
    private swing.controls.TextField txtNguoiLap;
    private swing.controls.TextField txtTT;
    private swing.controls.TextField txtTenKH;
    private swing.controls.TextField txtTienCoc;
    private swing.controls.TextField txtTongTien;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {
            try {
                fillTable(qlds.loadTableDV());
                Thread.sleep(1000);
            } catch (Exception e) {
                break;
            }
        }
    }
}
