/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.IntelliJTheme;
import global.Global;
import java.awt.Color;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import service.ServiceTaiKhoan;
import swing.event.EventMenuSelected;

/**
 *
 * @author sethk
 */
public class FormNhanVien extends javax.swing.JFrame {

    FormDatSan formDs;
    FormThongKe formTK;
    FormQLNV formQLNV;
    FormThanhToan formTT;
    FormGiaoCa formGc;
    FormService formSv;
    ServiceTaiKhoan qltk = new ServiceTaiKhoan();

    /**
     * Creates new form FormQuanLy
     */
    public FormNhanVien() {
        initComponents();

        lbAccount.removeAll();
        lbAccount.setText(qltk.getNameStaff(Global.getUser()));

        setBackground(new Color(0, 0, 0, 0));
        formDs = new FormDatSan();
        formTK = new FormThongKe();
        formQLNV = new FormQLNV();
        formTT = new FormThanhToan();
        formSv = new FormService();
        formGc = new FormGiaoCa();
        menu.initMoving(FormNhanVien.this);

        new FormDemThoiGianLam().setVisible(true);

        menu.addEventMenuSelected(new EventMenuSelected() {
            public void selected(int index) {
                if (index == 0) {
                    setForm(formDs);
                } else if (index == 1) {
                    setForm(formSv);
                } else if (index == 2) {
                    setForm(formTT);
                } else if (index == 3) {
                    setForm(formTK);
                } else if (index == 5) {
                    setForm(formGc);
                } else if (index == 9) {
                    JOptionPane.showMessageDialog(null, "Bạn không có quyền truy cập!");
                } else if (index == 10) {
                    JOptionPane.showMessageDialog(null, "Bạn không có quyền truy cập!");
                } else if (index == 11) {
                    JOptionPane.showMessageDialog(null, "Bạn không có quyền truy cập!");
                } else if (index == 12) {
                    JOptionPane.showMessageDialog(null, "Bạn không có quyền truy cập!");
                } else if (index == 13) {
                    JOptionPane.showMessageDialog(null, "Bạn không có quyền truy cập!");
                } else if (index == 14) {
                    JOptionPane.showMessageDialog(null, "Bạn không có quyền truy cập!");
                } else if (index == 16) {
                    logOut();
                }
            }
        });

        setForm(formDs);
        setForm(formDs);

    }

    private void setForm(JComponent com) {

        mainPanel.removeAll();
        mainPanel.add(com);
        mainPanel.repaint();
        mainPanel.revalidate();

    }

    public void logOut() {
        try {
            int choose = JOptionPane.showConfirmDialog(null, "Bạn có chắc là muốn đăng xuất", "Đóng ca", JOptionPane.YES_NO_CANCEL_OPTION);
            if (JOptionPane.YES_OPTION == choose) {
                Global.setKeyChucNang(true);
                this.dispose();
                new FormDangNhap().setVisible(true);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new swing.swing.PanelBorder();
        menu = new swing.swing.Menu();
        mainPanel = new javax.swing.JPanel();
        panelSeth1 = new swing.component.PanelSeth();
        lbAccount = new javax.swing.JLabel();
        button1 = new swing.controls.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        mainPanel.setOpaque(false);
        mainPanel.setLayout(new java.awt.BorderLayout());

        panelSeth1.setColor1(new java.awt.Color(48, 43, 99));
        panelSeth1.setColor2(new java.awt.Color(15, 12, 41));

        lbAccount.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbAccount.setForeground(new java.awt.Color(255, 255, 255));

        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/eye.png"))); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSeth1Layout = new javax.swing.GroupLayout(panelSeth1);
        panelSeth1.setLayout(panelSeth1Layout);
        panelSeth1Layout.setHorizontalGroup(
            panelSeth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeth1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSeth1Layout.setVerticalGroup(
            panelSeth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSeth1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelSeth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(panelSeth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 987, Short.MAX_VALUE))
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSeth1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        new FormThongTinCaNhan().setVisible(true);
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        IntelliJTheme.setup(FormDangNhap.class.getResourceAsStream("/Light.theme.json"));
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.controls.Button button1;
    private javax.swing.JLabel lbAccount;
    private javax.swing.JPanel mainPanel;
    private swing.swing.Menu menu;
    private swing.swing.PanelBorder panelBorder1;
    private swing.component.PanelSeth panelSeth1;
    // End of variables declaration//GEN-END:variables
}
